version: '2'
services:
  blacklisthotel-app:
    image: blacklisthotel
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://blacklisthotel-postgresql:5432/blacklisthotel
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  blacklisthotel-postgresql:
    extends:
      file: postgresql.yml
      service: blacklisthotel-postgresql
